name: Check Links

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose ./index.html ./assets/images/*.svg ./assets/images/*.png ./assets/images/*.webp 